# -*- coding: utf-8 -*-
"""Laju Pertumbuhan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157Mn582YNZvORymYXHWXvZjCBYV9rekS
"""

#import pustaka yang diperlukan
import numpy as np  #numpy adalah packages
import matplotlib.pyplot as plt  #. panggil struktur fungsi didalam packages

def pertumbuhan_populasi(t, P0, r):
  """
  Menyelesaikan P(t) = P0 * e^(r * t)

  Parameter:
    t : array-like, titik waktu
    P0 : float, populasi awal
    r : float, laju pertumbuhan

  Mengembalikan:
  P : array-like, populasi pada setiap titik waktu
  """
  return P0 * np.exp(r * t)

#Parameter contoh
P0 = 100
r = 0.1
t = np.linspace(0, 50, 200)
#Menyelesaikan persamaan
P = pertumbuhan_populasi(t, P0, r)

#Plot hasilnya
plt.figure(figsize=(8,6))
plt.plot(t, P, label=f"P(t) = {P0} * exp{r} * t)", color="blue")
plt.title("Pertumbuhan Populasi Seiring Waktu")
plt.xlabel("Waktu(t)")
plt.ylabel("Populasi (P)")
plt.legend()
plt.grid()
plt.show()