# -*- coding: utf-8 -*-
"""Model SEIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToUobmtI5pnguODIva-Tl6CQBCZjqGYC
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter SEIR
N = 1000  # Total populasi
beta = 0.3  # Laju penyebaran
sigma = 0.2  # Masa inkubasi
gamma = 0.1  # Laju pemulihan

# Kondisi awal
S0 = 985  # Rentan
E0 = 10    # Terpapar
I0 = 5    # Infeksi
R0 = 0    # Sembuh

# Sistem persamaan diferensial
def seir_model(y, t, N, beta, sigma, gamma):
    S, E, I, R = y
    dSdt = -beta * S * I / N
    dEdt = beta * S * I / N - sigma * E
    dIdt = sigma * E - gamma * I
    dRdt = gamma * I
    return [dSdt, dEdt, dIdt, dRdt]

# Waktu simulasi (dalam hari)
t = np.linspace(0, 160, 160)

# Solusi ODE
sol = odeint(seir_model, [S0, E0, I0, R0], t, args=(N, beta, sigma, gamma))
S, E, I, R = sol.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, E, label='Exposed', color='yellow')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Waktu (hari)')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR')
plt.legend()
plt.grid()
plt.show()