# -*- coding: utf-8 -*-
"""MODEL SEIR DENGAN KEMATIAN DAN KELAHIRAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWAyJ8obMfIiS8GlfoDODyuOn0OXIodK
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter model SEIRS (bisa disesuaikan dengan data dari jurnal)
N = 219501  # Total populasi
phi = 0.045   # Laju kelahiran
beta = 0.416 # Laju individu laten
mu = 0.045   # Laju kematian alami
alpha = 0.831 # Kematian akibat malaria
delta = 0.358 # Laju individu yang terinfeksi
omega = 1.0   # Efektivitas pengobatan
sigma = 0.500 # Laju pemulihan
gamma = 0.001 # Laju hilangnya kekebalan setelah sembuh

# Kondisi awal
S0 = 118983  # Individu rentan
E0 = 42653   # Individu yang terpapar
I0 = 49503   # Individu terinfeksi
R0 = 8362    # Individu yang sembuh

# Sistem persamaan diferensial untuk model SEIRS
def seirs_model(y, t, N, phi, beta, mu, alpha, delta, omega, sigma, gamma):
    S, E, I, R = y
    dSdt = phi + gamma * R - (mu + beta * I) * S
    dEdt = beta * I * S - (mu + omega + delta) * E
    dIdt = delta * E - (mu + alpha + sigma) * I
    dRdt = sigma * I + omega * E - (mu + gamma) * R
    return [dSdt, dEdt, dIdt, dRdt]

# Waktu simulasi
t = np.linspace(0, 48, 100)

# Solusi ODE
sol = odeint(seirs_model, [S0, E0, I0, R0], t, args=(N, phi, beta, mu, alpha, delta, omega, sigma, gamma))
S, E, I, R = sol.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, E, label='Exposed', color='orange')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Waktu (bulan)')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIRS Penyebaran Malaria')
plt.legend()
plt.grid()
plt.show()