# -*- coding: utf-8 -*-
"""Nilai_Eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUwxydRM7grLjPSCYdQ1XwpfArVn8nJZ
"""

import numpy as np

A = np.array([[4, 1],
             [2, 3]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\vektoreigen:")
print(vektoreigen)