# -*- coding: utf-8 -*-
"""Perubahan Suhu Kopi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rJ5m_ppSBDH6BGoGF-ntiUvKDC5Cqlq
"""

#import pustaka yang diperlukan
import numpy as np  #numpy adalah packages
import matplotlib.pyplot as plt  #. panggil struktur fungsi didalam packages

def Suhu_Kopi(Ta, T0, t, k):
  """
  Menyelesaikan T(t) = Ta + e^(-k * t) * T0

  Parameter:
    t  : array-like, waktu
    Ta : float, suhu ruangan
    T0 : float, suhu awal
    k  : float, konstanta laju pendinginan

  Mengembalikan:
  T : array-like, suhu
  """
  return Ta + np.exp(-k * t) * T0

#Parameter contoh
Ta = 25
T0 = 50
k  = 0.05
t  = np.linspace(0, 50, 100)

#Menyelesaikan persamaan
T = Suhu_Kopi(Ta, T0, t, k)

#Plot hasilnya
plt.figure(figsize=(8,6))
plt.plot(t, T, label=f"T(t) = {Ta} + exp(-{k} * t) * {T0}", color="green")
plt.title("Perubahan Suhu Kopi Terhadap Suhu Ruang")
plt.xlabel("Waktu (t)")
plt.ylabel("Suhu (T)")
plt.legend()
plt.grid()
plt.show()